apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.11.0
    helm:
      releaseName: certmanager
      values: |
        installCRDs: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: certmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true