apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.52.4
    helm:
      releaseName: grafana
      values: |
        adminUser: grafana
        adminPassword: grafana
        datasources:
          datasources1.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              uid: Prometheus
              url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
              access: proxy
              jsonData:
                httpMethod: POST
                manageAlerts: true
                prometheusType: Prometheus
          datasources2.yaml:
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              uid: Loki
              url: http://loki-gateway.logging
              access: proxy
              jsonData:
                maxLines: 1000
                derivedFields:
                  - datasourceUid: 'Tempo'
                    matcherRegex: '"request_X-B3-Traceid":"(\w+)"'
                    name: TraceID
                    url: $${__value.raw}
          datasources3.yaml:
            apiVersion: 1
            datasources:
            - name: Tempo
              type: tempo
              uid: Tempo
              url: http://tempo-distributed-query-frontend.tracing:3100
              access: proxy
              orgId: 1
              basicAuth: false
              version: 1
              editable: false
              jsonData:
                httpMethod: GET
                tracesToLogs:
                  datasourceUid: 'Loki'
                  tags: ['job', 'instance', 'pod', 'namespace']
                  mappedTags: [{ key: 'service.name', value: 'service' }]
                  mapTagNamesEnabled: false
                  spanStartTimeShift: '1h'
                  spanEndTimeShift: '1h'
                  filterByTraceID: false
                  filterBySpanID: false
                tracesToMetrics:
                  datasourceUid: 'Prometheus'
                  tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
                  queries:
                    - name: 'Sample query'
                      query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
                serviceMap:
                  datasourceUid: 'Prometheus'
                search:
                  hide: false
                nodeGraph:
                  enabled: true
                lokiSearch:
                  datasourceUid: 'Loki'
        dashboards:
          default:
            prometheus-stats:
              gnetId: 2
              revision: 2
              datasource: Prometheus
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true