apiVersion: v1
kind: Service
metadata:
  name: loki-lb
  namespace: logging
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  type: LoadBalancer
  loadBalancerIP: 192.168.11.144
