apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.47.1
    helm:
      releaseName: loki
      values: |
        loki:
          # Disable multi-tenant support
          auth_enabled: false
        
          # S3 backend storage configuration
          storage:
            bucketNames:
              chunks: k8s-loki
              ruler: k8s-loki
            type: s3
            s3:
              endpoint: minio.minio:9000
              region: eu-west-1
              secretAccessKey: minio123
              accessKeyId: minio
              s3ForcePathStyle: true
              insecure: true
              http_config:
                idle_conn_timeout: 90s
                response_header_timeout: 0s
                insecure_skip_verify: true
        
        # Configuration for the write
        write:
          # Number of replicas for the write
          replicas: 2
          persistence:
            # -- Size of persistent disk
            size: 10Gi
            # -- Storage class to be used.
            storageClass: nfs-share
        
          # Enable environment variables in config file
          # https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration
          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: MINIO_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-minio-secret
                  key: MINIO_ACCESS_KEY_ID
            - name: MINIO_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-minio-secret
                  key: MINIO_SECRET_ACCESS_KEY
        
        # Configuration for the read
        read:
          # Number of replicas for the read
          replicas: 2
          persistence:
            # -- Size of persistent disk
            size: 10Gi
            # -- Storage class to be used.
            storageClass: nfs-share
        
          # Enable environment variables in config file
          # https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration
          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: MINIO_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-minio-secret
                  key: MINIO_ACCESS_KEY_ID
            - name: MINIO_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-minio-secret
                  key: MINIO_SECRET_ACCESS_KEY
        
        # Configuration for the gateway
        gateway:
          # -- Specifies whether the gateway should be enabled
          enabled: true
          # -- Number of replicas for the gateway
          replicas: 1
        
        # Disable mino installation
        minio:
          enabled: false
        
        # Disable self-monitoring
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
              enabled: false
        
        # Disable helm-test
        test:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true