apiVersion: v1
kind: Service
metadata:
  name: loki-lb
  namespace: logging
spec:
  ports:
  - name: loki-port
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app.kubernetes.io/component: write
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  type: LoadBalancer
  loadBalancerIP: 192.168.11.144
