apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  rootUser: bWluaW8=
  rootPassword: bWluaW8xMjM=
  lokiPassword: bG9raVBhc3N3b3Jk
  tempoPassword: dGVtcG9QYXNzd29yZA==