apiVersion: v1
kind: Service
metadata:
  name: minio-lb
  namespace: minio
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio
    release: minio
  type: LoadBalancer
  loadBalancerIP: 192.168.11.143