apiVersion: v1
kind: Service
metadata:
  name: tempo-lb
  namespace: tracing
spec:
  ports:
  - name: http
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    app.kubernetes.io/component: distributor
    app.kubernetes.io/instance: tempo-distributed
    app.kubernetes.io/name: tempo
  type: LoadBalancer
  loadBalancerIP: 192.168.11.145
