- name: Install
  shell: curl https://raw.githubusercontent.com/fluent/fluent-bit/master/install.sh | sh

- name: Copy fluent-bit.conf
  copy:
    src: ./files/fluent-bit.conf
    dest: /etc/fluent-bit/
    mode: '0755'
    remote_src: yes
  ignore_errors: yes

- name: fluent-bit is running
  systemd:
    name: fluent-bit
    state: started
    enabled: true
  ignore_errors: yes