- name: Create folder
  file:
    path: "/etc/apt/keyrings/"
    state: directory
    mode: "755"

- name: wget
  shell: wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg

- name: echo
  shell: echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list

- name: Update Upgrade
  apt:
    upgrade: yes
    update_cache: true

- name: Install the package
  apt:
    name:
    - grafana-agent
  ignore_errors: yes

- name: Copy ha-backup.sh
  copy:
    src: "./files/grafana-agent.yaml"
    dest: /etc/
    mode: '0755'

- name: grafana-agent is running
  systemd:
    name: grafana-agent
    state: started
    enabled: true