- name: gpg
  shell: sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69

- name: echo
  shell: echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list

- name: Update Upgrade
  apt:
    upgrade: yes
    update_cache: true

- name: Install the package
  apt:
    name:
    - k6
  ignore_errors: yes