---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: certmanager
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
  - ca-issuers.yml